sbatch jobs.sh storage/41-avdsr-trained-boxing-5e-4-1e5.weights
sbatch jobs.sh storage/41-avdsr-trained-boxing-5e-4-1e5.weights
sbatch jobs.sh storage/41-avdsr-trained-boxing-5e-4-1e5.weights
sbatch jobs.sh storage/41-avdsr-trained-boxing-5e-4-1e5-shuffle.weights
sbatch jobs.sh storage/41-avdsr-trained-boxing-5e-4-1e5-shuffle.weights
sbatch jobs.sh storage/41-avdsr-trained-boxing-5e-4-1e5-shuffle.weights
sbatch jobs.sh default
sbatch jobs.sh default
sbatch jobs.sh default